// <auto-generated />
using System;
using FoodSafetyTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodSafetyTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323143122_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FoodSafetyTracker.Models.FollowUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("InspectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId");

                    b.ToTable("FollowUps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DueDate = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            DueDate = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            DueDate = new DateTime(2024, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            DueDate = new DateTime(2024, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 7,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            DueDate = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 9,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            DueDate = new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 10,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            DueDate = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 13,
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            ClosedDate = new DateTime(2024, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2024, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 14,
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            ClosedDate = new DateTime(2024, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2024, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            ClosedDate = new DateTime(2024, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InspectionId = 21,
                            Status = 1
                        });
                });

            modelBuilder.Entity("FoodSafetyTracker.Models.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PremisesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PremisesId");

                    b.ToTable("Inspections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InspectionDate = new DateTime(2024, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Poor hygiene in kitchen",
                            Outcome = 1,
                            PremisesId = 1,
                            Score = 42
                        },
                        new
                        {
                            Id = 2,
                            InspectionDate = new DateTime(2024, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Expired food found",
                            Outcome = 1,
                            PremisesId = 1,
                            Score = 55
                        },
                        new
                        {
                            Id = 3,
                            InspectionDate = new DateTime(2024, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Good overall",
                            Outcome = 0,
                            PremisesId = 2,
                            Score = 85
                        },
                        new
                        {
                            Id = 4,
                            InspectionDate = new DateTime(2024, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Minor issues noted",
                            Outcome = 0,
                            PremisesId = 2,
                            Score = 70
                        },
                        new
                        {
                            Id = 5,
                            InspectionDate = new DateTime(2024, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Outcome = 0,
                            PremisesId = 3,
                            Score = 92
                        },
                        new
                        {
                            Id = 6,
                            InspectionDate = new DateTime(2024, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Pest evidence found",
                            Outcome = 1,
                            PremisesId = 4,
                            Score = 38
                        },
                        new
                        {
                            Id = 7,
                            InspectionDate = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Temperature violations",
                            Outcome = 1,
                            PremisesId = 4,
                            Score = 60
                        },
                        new
                        {
                            Id = 8,
                            InspectionDate = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Excellent cleanliness",
                            Outcome = 0,
                            PremisesId = 5,
                            Score = 88
                        },
                        new
                        {
                            Id = 9,
                            InspectionDate = new DateTime(2024, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Storage issues",
                            Outcome = 1,
                            PremisesId = 6,
                            Score = 45
                        },
                        new
                        {
                            Id = 10,
                            InspectionDate = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Cross-contamination risk",
                            Outcome = 1,
                            PremisesId = 6,
                            Score = 50
                        },
                        new
                        {
                            Id = 11,
                            InspectionDate = new DateTime(2024, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Outcome = 0,
                            PremisesId = 7,
                            Score = 95
                        },
                        new
                        {
                            Id = 12,
                            InspectionDate = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Good practices",
                            Outcome = 0,
                            PremisesId = 8,
                            Score = 72
                        },
                        new
                        {
                            Id = 13,
                            InspectionDate = new DateTime(2024, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Multiple violations",
                            Outcome = 1,
                            PremisesId = 9,
                            Score = 33
                        },
                        new
                        {
                            Id = 14,
                            InspectionDate = new DateTime(2024, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "No hand wash station",
                            Outcome = 1,
                            PremisesId = 9,
                            Score = 48
                        },
                        new
                        {
                            Id = 15,
                            InspectionDate = new DateTime(2024, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Outcome = 0,
                            PremisesId = 10,
                            Score = 90
                        },
                        new
                        {
                            Id = 16,
                            InspectionDate = new DateTime(2024, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Satisfactory",
                            Outcome = 0,
                            PremisesId = 11,
                            Score = 78
                        },
                        new
                        {
                            Id = 17,
                            InspectionDate = new DateTime(2024, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Outcome = 0,
                            PremisesId = 12,
                            Score = 88
                        },
                        new
                        {
                            Id = 18,
                            InspectionDate = new DateTime(2024, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Good",
                            Outcome = 0,
                            PremisesId = 3,
                            Score = 80
                        },
                        new
                        {
                            Id = 19,
                            InspectionDate = new DateTime(2024, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Outcome = 0,
                            PremisesId = 5,
                            Score = 65
                        },
                        new
                        {
                            Id = 20,
                            InspectionDate = new DateTime(2024, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Outcome = 0,
                            PremisesId = 7,
                            Score = 91
                        },
                        new
                        {
                            Id = 21,
                            InspectionDate = new DateTime(2024, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Old violations",
                            Outcome = 1,
                            PremisesId = 8,
                            Score = 55
                        },
                        new
                        {
                            Id = 22,
                            InspectionDate = new DateTime(2023, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Outcome = 0,
                            PremisesId = 10,
                            Score = 82
                        },
                        new
                        {
                            Id = 23,
                            InspectionDate = new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Outcome = 0,
                            PremisesId = 11,
                            Score = 74
                        },
                        new
                        {
                            Id = 24,
                            InspectionDate = new DateTime(2024, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Outcome = 0,
                            PremisesId = 12,
                            Score = 85
                        },
                        new
                        {
                            Id = 25,
                            InspectionDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Recent check",
                            Outcome = 0,
                            PremisesId = 2,
                            Score = 79
                        });
                });

            modelBuilder.Entity("FoodSafetyTracker.Models.Premises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RiskRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Premises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1 Main St",
                            Name = "Le Bon Goût",
                            RiskRating = 2,
                            Town = "Cork"
                        },
                        new
                        {
                            Id = 2,
                            Address = "5 Shop St",
                            Name = "Pizza Palace",
                            RiskRating = 1,
                            Town = "Dublin"
                        },
                        new
                        {
                            Id = 3,
                            Address = "12 Park Ave",
                            Name = "Green Bowl Café",
                            RiskRating = 0,
                            Town = "Galway"
                        },
                        new
                        {
                            Id = 4,
                            Address = "8 High St",
                            Name = "The Burger Joint",
                            RiskRating = 2,
                            Town = "Cork"
                        },
                        new
                        {
                            Id = 5,
                            Address = "22 Grafton St",
                            Name = "Sushi Express",
                            RiskRating = 1,
                            Town = "Dublin"
                        },
                        new
                        {
                            Id = 6,
                            Address = "3 Harbour Rd",
                            Name = "Ocean Catch",
                            RiskRating = 2,
                            Town = "Galway"
                        },
                        new
                        {
                            Id = 7,
                            Address = "17 Bridge St",
                            Name = "Corner Bakery",
                            RiskRating = 0,
                            Town = "Cork"
                        },
                        new
                        {
                            Id = 8,
                            Address = "9 Temple Bar",
                            Name = "Noodle House",
                            RiskRating = 1,
                            Town = "Dublin"
                        },
                        new
                        {
                            Id = 9,
                            Address = "45 Eyre Sq",
                            Name = "The Kebab King",
                            RiskRating = 2,
                            Town = "Galway"
                        },
                        new
                        {
                            Id = 10,
                            Address = "6 Patrick St",
                            Name = "Sunny Side Up",
                            RiskRating = 0,
                            Town = "Cork"
                        },
                        new
                        {
                            Id = 11,
                            Address = "33 O'Connell St",
                            Name = "Taco Town",
                            RiskRating = 1,
                            Town = "Dublin"
                        },
                        new
                        {
                            Id = 12,
                            Address = "2 Quay St",
                            Name = "The Vegan Spot",
                            RiskRating = 0,
                            Town = "Galway"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FoodSafetyTracker.Models.FollowUp", b =>
                {
                    b.HasOne("FoodSafetyTracker.Models.Inspection", "Inspection")
                        .WithMany("FollowUps")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("FoodSafetyTracker.Models.Inspection", b =>
                {
                    b.HasOne("FoodSafetyTracker.Models.Premises", "Premises")
                        .WithMany("Inspections")
                        .HasForeignKey("PremisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Premises");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodSafetyTracker.Models.Inspection", b =>
                {
                    b.Navigation("FollowUps");
                });

            modelBuilder.Entity("FoodSafetyTracker.Models.Premises", b =>
                {
                    b.Navigation("Inspections");
                });
#pragma warning restore 612, 618
        }
    }
}
